text = input("введите любой текст: ")
text_split = text.split(" ")
text_join = "--".join(text_split)
text_find = text.find("-",3,7)
# text_index = text.index("-",3,7)
text_count = text.count("а")
text_partition = text.partition("ет")
print(text_find)
text_replace = text.replace(" ", "+")
text_isdigit = text.isdigit()
text_isalpha = text.isalpha()
text_isalnum = text.isalnum()
text_isidentifier = text.isidentifier()
text_isspace = text.isspace()
text_istitle = text.istitle()
text_islower = text.islower()
text_title= text.title()
text_expantabs = text.expandtabs(15)
text_strpis = text.strip()
text_removeprefix = text.removesuffix(" ")
text_center = text.center(5,"-")
text_zfill = text.zfill(10)
text_ljust = text.ljust(10,"-")
text_encode = text.encode()
a= 15
b= 16
c= (a|b)
print(c)


print(text_strpis)
print(text_removeprefix)
print(text_center)
print(text_zfill)
print(text_ljust)
print(text_encode)


# print(text_index)
# print(text_count)
# print(text_replace)
# print(text_isdigit)
# print(text_isalpha)
# print(text_isalnum)
# print(text_isidentifier)
# print(text_isspace)
# print(text_istitle)
# print(text_islower)
# print(text_title)
# print(text.capitalize())
# print(text_expantabs)
